/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpillertojRouteImport } from './routes/spillertoj'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeAltSahRouteImport } from './routes/se-alt-sah'
import { Route as ReadmeRouteImport } from './routes/readme'
import { Route as MerchandiseRouteImport } from './routes/merchandise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduktSlugRouteImport } from './routes/produkt.$slug'

const SpillertojRoute = SpillertojRouteImport.update({
  id: '/spillertoj',
  path: '/spillertoj',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeAltSahRoute = SeAltSahRouteImport.update({
  id: '/se-alt-sah',
  path: '/se-alt-sah',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadmeRoute = ReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchandiseRoute = MerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktSlugRoute = ProduktSlugRouteImport.update({
  id: '/produkt/$slug',
  path: '/produkt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchandise': typeof MerchandiseRoute
  '/readme': typeof ReadmeRoute
  '/se-alt-sah': typeof SeAltSahRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spillertoj': typeof SpillertojRoute
  '/produkt/$slug': typeof ProduktSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchandise': typeof MerchandiseRoute
  '/readme': typeof ReadmeRoute
  '/se-alt-sah': typeof SeAltSahRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spillertoj': typeof SpillertojRoute
  '/produkt/$slug': typeof ProduktSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merchandise': typeof MerchandiseRoute
  '/readme': typeof ReadmeRoute
  '/se-alt-sah': typeof SeAltSahRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spillertoj': typeof SpillertojRoute
  '/produkt/$slug': typeof ProduktSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/merchandise'
    | '/readme'
    | '/se-alt-sah'
    | '/sitemap.xml'
    | '/spillertoj'
    | '/produkt/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/merchandise'
    | '/readme'
    | '/se-alt-sah'
    | '/sitemap.xml'
    | '/spillertoj'
    | '/produkt/$slug'
  id:
    | '__root__'
    | '/'
    | '/merchandise'
    | '/readme'
    | '/se-alt-sah'
    | '/sitemap.xml'
    | '/spillertoj'
    | '/produkt/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchandiseRoute: typeof MerchandiseRoute
  ReadmeRoute: typeof ReadmeRoute
  SeAltSahRoute: typeof SeAltSahRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpillertojRoute: typeof SpillertojRoute
  ProduktSlugRoute: typeof ProduktSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spillertoj': {
      id: '/spillertoj'
      path: '/spillertoj'
      fullPath: '/spillertoj'
      preLoaderRoute: typeof SpillertojRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/se-alt-sah': {
      id: '/se-alt-sah'
      path: '/se-alt-sah'
      fullPath: '/se-alt-sah'
      preLoaderRoute: typeof SeAltSahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readme': {
      id: '/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof ReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandise': {
      id: '/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof MerchandiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$slug': {
      id: '/produkt/$slug'
      path: '/produkt/$slug'
      fullPath: '/produkt/$slug'
      preLoaderRoute: typeof ProduktSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchandiseRoute: MerchandiseRoute,
  ReadmeRoute: ReadmeRoute,
  SeAltSahRoute: SeAltSahRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpillertojRoute: SpillertojRoute,
  ProduktSlugRoute: ProduktSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
